pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'   # <- THIS installs .NET 8
      installationPath: $(Agent.ToolsDirectory)/dotnet


  - script: dotnet build --configuration Release
    displayName: 'Build Project'

  - script: dotnet test --logger trx
    displayName: 'Run Tests'
